/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActivityLogDetail: typeof import('./src/pages/system/components/ActivityLogDetail.vue')['default']
    AlbumItems: typeof import('./src/pages/cdn/albums/components/AlbumItems.vue')['default']
    AlbumItemUpdate: typeof import('./src/pages/cdn/albums/components/AlbumItemUpdate.vue')['default']
    AlbumUpsert: typeof import('./src/pages/cdn/albums/components/AlbumUpsert.vue')['default']
    AppBreadcrumb: typeof import('./src/components/layout/AppBreadcrumb.vue')['default']
    AppMenu: typeof import('./src/components/layout/AppMenu.vue')['default']
    AppMenuItem: typeof import('./src/components/layout/AppMenuItem.vue')['default']
    AppSidebar: typeof import('./src/components/layout/AppSidebar.vue')['default']
    AppTopbar: typeof import('./src/components/layout/AppTopbar.vue')['default']
    AttendeeList: typeof import('./src/pages/cms/attendees/components/AttendeeList.vue')['default']
    AttendeeTimelineDialog: typeof import('./src/pages/cms/attendees/components/AttendeeTimelineDialog.vue')['default']
    ChangePassword: typeof import('./src/components/layout/ChangePassword.vue')['default']
    DateRangePicker: typeof import('./src/components/ui/DateRangePicker.vue')['default']
    FileManager: typeof import('./src/components/file-manager/FileManager.vue')['default']
    FileManagerDialog: typeof import('./src/components/file-manager/FileManagerDialog.vue')['default']
    ImagePicker: typeof import('./src/components/ui/ImagePicker.vue')['default']
    ImageViewer: typeof import('./src/components/ui/ImageViewer.vue')['default']
    LanguageSelection: typeof import('./src/components/layout/LanguageSelection.vue')['default']
    MCkEditor: typeof import('./src/components/ui/m-ck-editor.vue')['default']
    MenuButton: typeof import('./src/components/ui/MenuButton.vue')['default']
    NewFolderDialog: typeof import('./src/components/file-manager/NewFolderDialog.vue')['default']
    RenameDialog: typeof import('./src/components/file-manager/RenameDialog.vue')['default']
    RolePermissions: typeof import('./src/pages/system/components/RolePermissions.vue')['default']
    RoleUpsert: typeof import('./src/pages/system/components/RoleUpsert.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StateCheckbox: typeof import('./src/components/ui/StateCheckbox.vue')['default']
    UploadTicketsDialog: typeof import('./src/pages/cms/tickets/components/UploadTicketsDialog.vue')['default']
    UserResetPassword: typeof import('./src/pages/system/components/UserResetPassword.vue')['default']
    UserUpsert: typeof import('./src/pages/system/components/UserUpsert.vue')['default']
  }
}
